

# Visualizations

## 1. stationary signals = vertical lines

```{r}
omega  <- 0.25

# time domain
c.constant <- rep(1,N)

# freq domain --- mtm
y.t <- ts(cos(2*pi*omega*t))
y.f <- spec.mtm(y.t)

# sgram
sgram.stationary <- outer(y.f$spec, c.constant)
image.plot(sgram.stationary, xlab = "freq", ylab = "time")
mtext("Stationary signal: multitaper (outer prod. of signal and vec of 1s)")
```

```{r}
get <- function(){ y.t }

pbc.stationary <- p.bc()
image.plot(f,t,pbc.stationary$bc1[,,1], xlab = "freq", ylab = "time")
mtext("stationary signal: 1-BC")
```

## 2. UMP signals fade in and out, still vertical

```{r}
c.gauss <- ct$center$norm

# theoretical
sgram.ump <- outer(y.f$spec, c.gauss)
image.plot(sgram.ump, xlab = "freq", ylab = "time")
mtext("UMP signal: theoretical (outer prod. of c(t) and multitaper)")

# pbc
get <- function(){ c.gauss*y.t }

pbc.ump <- p.bc()
image.plot(f,t,pbc.ump$bc1[,,1], xlab = "freq", ylab = "time")
mtext("UMP signal: 1-BC")
```


## 2. Freq. modulated signals = diagonal lines

```{r}
omega.t <- seq(0.05,0.45,length.out = N)
y.t     <- ts(cos(2*pi*omega.t*t)) # + cos(2*pi*0.5*omega.t*t) + cos(2*pi*0.25*omega.t*t))

get <- function(){ y.t }

pbc.fmod <- p.bc(B = 50)
image.plot(f,t,pbc.fmod$bc1[,,1], xlab = "freq", ylab = "time ->")
mtext("Stationary signal: 1-BC")
```


## 3. Freq AND amp. modulated signals = diag lines in and out

```{r}
omega.t <- seq(0.05,0.45,length.out = N)*0.5
y.t     <- ts(cos(2*pi*omega.t*t)) # + cos(2*pi*0.5*omega.t*t) + cos(2*pi*0.25*omega.t*t))

get <- function(){ y.t*c.gauss + rnorm(N)}

pbc.fmod <- p.bc()
image.plot(f,t,pbc.fmod$bc1[,,1], xlab = "freq", ylab = "time ->")
mtext("amplitude modulation + freq modulation + noise")
```

```{r}
omega.t <- seq(0.05,0.45,length.out = N)*0.5
y.t     <- ts(cos(2*pi*omega.t*t) + cos(2*pi*0.5*omega.t*t) + cos(2*pi*0.25*omega.t*t))

get <- function(){ y.t*c.gauss }

pbc.fmod <- p.bc()
image.plot(f,t,pbc.fmod$bc1[,,1], xlab = "freq", ylab = "time ->")
mtext("overlapping pbc bandwidths")
```

```{r}
omega.t <- seq(0.05,0.45,length.out = N)
y.t     <- ts(cos(2*pi*omega.t*t) + cos(2*pi*0.66*omega.t*t) + cos(2*pi*0.33*omega.t*t))

get <- function(){ y.t }

pbc.fmod <- p.bc()
image.plot(f,t,pbc.fmod$bc1[,,1], xlab = "freq", ylab = "time ->")
```





